[deployment]
build = ["node", "deploy-clean.cjs", "build"]
run = ["node", "deploy-clean.cjs", "start"]
deploymentTarget = "cloudrun"

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80
