[deployment]
build = ["sh", "-c", "npx vite build && npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"]
run = ["sh", "-c", "NODE_ENV=production node dist/index.js"]
deploymentTarget = "cloudrun"

[env]
NODE_ENV = "production"

[[ports]]
localPort = 5000
externalPort = 80
